---
title: "Potential code flow"
subtitle: "data-examples/example_data_GPS.csv"
author: "Einar Hjörleifsson"
date: "`r lubridate::today()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Preambles

```{r all_stuff_needed}
library(sf)
library(tidyverse)
source("R/ramb_functions.R")
```


Tend to like short-names (less typing donwstream):
```
vid:  vessel id
time: the ais clock
hid:  harbour id
gid:  gear id
tid:  trip id
```
## Preprocessing

### Get data

```{r data}
hb <- 
  read_rds("data/harbours.rds") %>% 
  # give each harbour a unique id
  mutate(hid = 1:n()) %>% 
  select(hid)
d <- 
  read_csv("data-examples/example_data_GPS.csv") %>% 
  # less typing downstream
  rename(vid = vessel_id,
         gid = gear)
nrow0 <- nrow(d)  # sanity check downstream
```

### Ping in harbour and trip assignment

```{r distinct_harbour_and_trips}
d <- 
  d %>% 
  # just to be sure
  arrange(vid, time) %>% 
  # may be of use downstream
  mutate(.rid = 1:n()) %>% 
  select(.rid, everything())
print(paste("rows in: ", nrow0, " rows out: ", nrow(d)))
# time needs to be distinct ----------------------------------------------------
d <-
  d %>% 
  # time has to be unique witin a vessel
  #  may want to investigate why this happens and also which duplicate point to keep
  distinct(vid, time, .keep_all = TRUE) 
print(paste("rows in: ", nrow0, " rows out: ", nrow(d)))
nrow0 <- nrow(d) # start again
# point in polygon (vessel in harbour) and trips -------------------------------
d <-
  d %>% 
  # get harbour id
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326,
           remove = FALSE) %>% 
  st_join(hb) %>% 
  st_drop_geometry() %>% 
  mutate(tid = rb_define_trips(vid, hid))
print(paste("rows in: ", nrow0, " rows out: ", nrow(d)))
```

```{r trip_overview}
d %>% 
  count(vid, tid) %>% 
  spread(vid, n) %>% 
  knitr::kable(caption = "Overview of trips by vessels (negative values are harbour 'trips').")
```

So, only 1 trip per vessel - harbour pings already filtered out. Could do:

* Assign trips based on time gap

### Whacky points

```{r whacky_points}
# whacky points ----------------------------------------------------------------
d <- 
  d %>% 
  group_by(vid, tid) %>% 
  mutate(n = n()) %>% 
  #     step speed (nmi)
  mutate(ss = ifelse(n > 2 & tid > 0,
                     rb_arcdist(lat, lon, lead(lat), lead(lon)) / as.numeric(difftime(lead(time), time, units = "hours")),
                     NA_real_)) %>%
  # vmask may crash if put together with other things inside a mutate
  #  even then, seems to be a bit shaky
  #  slow, even for reasonable amount of ais data [volunteering for code optimization??]
  #  need a miminum of six points for vmask, see help file to get info what functions does
  mutate(wacky = ifelse(n >= 6 & tid > 0,
                        argosfilter::vmask(lat, lon, time, vmax = 13),  # m/s ~ 25 knots
                        NA)) %>% 
  ungroup() %>% 
  select(-n)
print(paste("rows in: ", nrow0, " rows out: ", nrow(d)))
```

```{r}
d %>% count(wacky)
```

So nice and neat data :-)

```{r whacky_peek, fig.height = 9}
d %>% 
  # just for visuals
  mutate(ss = ifelse(ss > 30, 30, ss),
         wacky = ifelse(wacky == "removed", TRUE, FALSE),
         size = ifelse(wacky, 1, 0.01)) %>% 
  ggplot(aes(time)) +
  theme_bw() +
  geom_point(aes(y = speed), size = 1, colour = "grey") +
  geom_point(aes(y = ss, colour = as_factor(wacky), size = size),
             alpha = 0.5) +
  scale_size_area(max_size = 2) +
  facet_wrap(~ vid, scales = "free_x", ncol = 3) +
  scale_colour_brewer(palette = "Set1") +
  theme(legend.position = "none") +
  labs(x = NULL, y = "kn")
```

Hmm, data obviously has time gaps, indicate trips

## Assigning pings to behaviour

### Speed alone

### Modeling
